/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hp4
 */
public class Consultar1 extends javax.swing.JFrame {

    /**
     * Creates new form Consultar1
     */
    DefaultTableModel model;
    
    public Consultar1() {
        initComponents();
        limpiar1();
        cargagri1("");
        
        
        
        
    }    
    
    
    void hora(){
    
        LocalTime hora1 = LocalTime.now();
        DateTimeFormatter h = DateTimeFormatter.ofPattern("HH':'mm ' HS'");
        hora.setText(hora1.format(h) + "");
    }
    
    void fecha(){
    
        LocalDate fecha1 = LocalDate.now();
        DateTimeFormatter h = DateTimeFormatter.ofPattern("dd '/' MMM '/' yyyy");
        fecha.setText(fecha1.format(h) + "");
    }
    void limpiar1(){
        nombre.setText("");
        apellido.setText("");
        documento.setText("");
        hora.setText("");
        fecha.setText("");
        buscarcliente.setText("");
    }
    
    void cargagri1(String valor){
        String[]titulos={"ID","Nombre","Apellido","Documento"};
        String[]registro=new String[4];
        model= new DefaultTableModel(null,titulos);
        String sql="SELECT*FROM personal WHERE documento LIKE '%"+valor+"%'";
        
        try { 
            String db="net.ucanaccess.jdbc.UcanaccessDriver";
            Connection cn;
            cn = DriverManager.getConnection("jdbc:ucanaccess://E://Programacion//PRUEBA//TP JAVA//registro.accdb");
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
        
            while(rs.next()){
                registro[0]=rs.getString("id_profesores");
                registro[1]=rs.getString("nombre");
                registro[2]=rs.getString("apellido");
                registro[3]=rs.getString("documento");
                model.addRow(registro);
            }
            
            jTable1.setModel(model);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
  
    }
    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buscarcliente = new javax.swing.JTextField();
        documento = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ingreso = new javax.swing.JButton();
        retiro = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(22, 23, 29));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 33, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INGRESE SU DOCUMENTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        buscarcliente.setBackground(new java.awt.Color(41, 46, 73));
        buscarcliente.setForeground(new java.awt.Color(255, 255, 255));
        buscarcliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscarcliente.setBorder(null);
        buscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarclienteActionPerformed(evt);
            }
        });
        buscarcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarclienteKeyReleased(evt);
            }
        });
        jPanel1.add(buscarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 120, 30));

        documento.setEditable(false);
        documento.setBackground(new java.awt.Color(41, 46, 73));
        documento.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        documento.setForeground(new java.awt.Color(255, 255, 255));
        documento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        documento.setBorder(null);
        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });
        jPanel1.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 120, 30));

        apellido.setEditable(false);
        apellido.setBackground(new java.awt.Color(41, 46, 73));
        apellido.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        apellido.setForeground(new java.awt.Color(255, 255, 255));
        apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido.setBorder(null);
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 120, 30));

        hora.setEditable(false);
        hora.setBackground(new java.awt.Color(41, 46, 73));
        hora.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        hora.setForeground(new java.awt.Color(255, 255, 255));
        hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hora.setBorder(null);
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 120, 30));

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(41, 46, 73));
        fecha.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha.setBorder(null);
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 120, 30));

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(41, 46, 73));
        nombre.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(null);
        nombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 120, 30));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FECHA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 78, 30));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOMBRE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 80, 30));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" APELLIDO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 107, 30));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" DOCUMENTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HORA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 80, 30));

        jButton1.setBackground(new java.awt.Color(72, 85, 99));
        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mostrar todos");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 140, 30));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("S. CONTROL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 180, 48));

        jPanel2.setBackground(new java.awt.Color(22, 23, 29));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreso.setBackground(new java.awt.Color(72, 85, 99));
        ingreso.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        ingreso.setForeground(new java.awt.Color(255, 255, 255));
        ingreso.setText("INGRESO");
        ingreso.setBorderPainted(false);
        ingreso.setFocusPainted(false);
        ingreso.setOpaque(false);
        ingreso.setPreferredSize(new java.awt.Dimension(60, 20));
        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });
        jPanel2.add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 30));

        retiro.setBackground(new java.awt.Color(72, 85, 99));
        retiro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        retiro.setForeground(new java.awt.Color(255, 255, 255));
        retiro.setText("RETIRO");
        retiro.setBorder(null);
        retiro.setBorderPainted(false);
        retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiroActionPerformed(evt);
            }
        });
        jPanel2.add(retiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 30));

        nuevo.setBackground(new java.awt.Color(72, 85, 99));
        nuevo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        nuevo.setForeground(new java.awt.Color(255, 255, 255));
        nuevo.setText("BORRAR");
        nuevo.setBorderPainted(false);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel2.add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 30));

        salir.setBackground(new java.awt.Color(72, 85, 99));
        salir.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("SALIR");
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel2.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 100, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ingreso.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 50, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/retiro.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/borrar.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 30));

        admin.setBackground(new java.awt.Color(72, 85, 99));
        admin.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("ADMIN");
        admin.setBorderPainted(false);
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel2.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        jTable1.setBackground(new java.awt.Color(187, 210, 197));
        jTable1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "DOCUMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
     limpiar1();
    }//GEN-LAST:event_nuevoActionPerformed

            
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void buscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarclienteActionPerformed

    private void buscarclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarclienteKeyReleased
        // TODO add your handling code here:
        cargagri1(buscarcliente.getText());
    }//GEN-LAST:event_buscarclienteKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargagri1("");
        buscarcliente.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        
        hora();
        fecha();
        
        String db="net.ucanaccess.jdbc.UcanaccessDriver";
        Connection cn;
        try { 
            cn = DriverManager.getConnection("jdbc:ucanaccess://E://Programacion//PRUEBA//TP JAVA//registro.accdb");
            Statement st = cn.createStatement();
            String sql = "insert into entrada(nombre,apellido,documento,hora,fecha)"
            +"values('"+this.nombre.getText()+"','"+this.apellido.getText()+"','"+this.documento.getText()+"','"+this.hora.getText()+"','"+this.fecha.getText()+"')";
            st.executeUpdate(sql);
            cargagri1("");
            nuevo.setEnabled(true);
            
                    
        } catch (Exception ex){
        System.out.println("Error");
        }
        
    }//GEN-LAST:event_ingresoActionPerformed

    private void retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiroActionPerformed

        hora();
        fecha();

        String db="net.ucanaccess.jdbc.UcanaccessDriver";
        Connection cn;
        try {
            cn = DriverManager.getConnection("jdbc:ucanaccess://E://Programacion//PRUEBA//TP JAVA//registro.accdb");
            Statement st = cn.createStatement();
            String sql = "insert into retiro(nombre,apellido,documento,hora,fecha)"
            +"values('"+this.nombre.getText()+"','"+this.apellido.getText()+"','"+this.documento.getText()+"','"+this.hora.getText()+"','"+this.fecha.getText()+"')";
            st.executeUpdate(sql);
            cargagri1("");
            nuevo.setEnabled(true);

        } catch (Exception ex){
            System.out.println("Error");
        }

    }//GEN-LAST:event_retiroActionPerformed

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int rec = this.jTable1.getSelectedRow();
        this.nombre.setText(jTable1.getValueAt(rec, 1).toString());
        this.apellido.setText(jTable1.getValueAt(rec, 2).toString());
        this.documento.setText(jTable1.getValueAt(rec, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        
        admin_login newframe = new admin_login();
        newframe.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField buscarcliente;
    private javax.swing.JTextField documento;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField hora;
    private javax.swing.JButton ingreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton retiro;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
